### PR TITLE
Setup CKEditor

### PR DESCRIPTION
**Pull request by hoangphucd3**
# Issue
Connect #20 

# Todo
- [x] Add CKEditor 5

# Note
 - This is an build version of CKEditor. Will need to update to stable version.

### CODE REVIEW

**Comment by jstep-techlog** [comment]
Can one of the admins verify this patch?

**Comment by jstep-techlog** [comment]
Misspell detected 8 issues on 7cd35cc807fda3e49c45a21fe9c7eef40b664690
Visit https://sideci.com/gh/116365859/pull_requests/21 to review the issues.

**Comment by jstep-techlog** [comment]
JSHint detected 7 issues on 7cd35cc807fda3e49c45a21fe9c7eef40b664690
Visit https://sideci.com/gh/116365859/pull_requests/21 to review the issues.

**Comment by hoangphucd3** [comment]
@jstep-techlog Issue related to 3rd js so I will close it.

**Pull request merged**
